CI/CD log creation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -121,8 +121,11 @@ jobs:
              chmod +x ./scripts/drivechain_testing.sh || echo "Function scrript not found, skipping chmod"        
              chmod +x ./scripts/config.sh || echo "Config script not found, skipping chmod"
 
-      - name: Run Tests
+      - name: Run Integration Tests
         run: ./scripts/integration_testing.sh || echo "Script not found, skipping tests"
+
+      - name: Drivechain Testing Output
+        run: ./scripts/drivechain_testing.sh || echo "Script not found, skipping tests"
 
   upload-artifacts-macos:
     name: Upload macOS artifacts to releases.drivechain.info
